### ISSUE TITLE
void

### ISSUE THREAD

**Issue by lazaridis-com** [totaljs/documentation#22]

**Comment by petersirka** [comment]
Thank you for your suggestion.

I don't want to add something like this `totaljs start` because it is useless. Each developer can start Total.js easily via `node debug.js` or `node release.js` or `node yourscript.js` commands, wrapping this functionality is useless (I think, it's my opinion).

`totaljs new` - it's not bad idea. I'll try to add similar functionality.

**Comment by lazaridis-com** [comment]
@petersirka, I was totally (total - totally) fascinated by your framework, and the overall concept of "ready applications". If you keep half of what the documentation describes, then this should become the no. 1 framework for node.js. 

But you have to see one thing: you have so deep knowledge of all this, that you cannot anymore judge things from the eye of a simple newcomer. As a developer I know that implementing wrappers is even annoying. As a user, i think different.

The main thing is to make things super-simple. Perhaps we should discuss this via email, there I could tell you some things of strategic/business matter, too. You have done really excellent work, it should not be blocked by details.

Finally, is there a way to contribute to the documentation via a repo? Or does this work directly via your internal CMS?

**Comment by lazaridis-com** [comment]
just saw your other message. will contact you via email.
